ALTER DEFAULT PRIVILEGES IN SCHEMA public
REVOKE USAGE, SELECT ON SEQUENCES FROM shopping_cart_employee;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
REVOKE SELECT, INSERT ON TABLES FROM shopping_cart_employee;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
REVOKE ALL PRIVILEGES ON SEQUENCES FROM shopping_cart_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
REVOKE ALL PRIVILEGES ON TABLES FROM shopping_cart_admin;

REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM shopping_cart_employee;
REVOKE SELECT, INSERT ON ALL TABLES IN SCHEMA public FROM shopping_cart_employee;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM shopping_cart_admin;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM shopping_cart_admin;

REVOKE USAGE ON SCHEMA public FROM shopping_cart_employee;
REVOKE USAGE ON SCHEMA public FROM shopping_cart_admin;

REVOKE CONNECT ON DATABASE shopping_cart_db FROM shopping_cart_employee;
REVOKE CONNECT ON DATABASE shopping_cart_db FROM shopping_cart_admin;
